import * as admin from 'firebase-admin'

// Initialize Firebase Admin once
admin.initializeApp()

export { chatWithAria } from './chat'
export { transcribeAudio, synthesizeSpeech } from './voice'
export { executeAction } from './executeAction'
export { sendTestNotification } from './notifications'
export { processDueReminders } from './processDueReminders'
export { generateDailyBriefing } from './briefing'
export { getPluginStatus } from './pluginStatus'
export {
  runWorkflowFn as runWorkflow,
  getWorkflowHistoryFn as getWorkflowHistory,
  listWorkflowsFn as listWorkflows,
  getWorkflowSchedulesFn as getWorkflowSchedules,
  setWorkflowEnabledFn as setWorkflowEnabled,
} from './workflowApi'
export { runAgentGraph, getAgentStatus } from './agentApi'
export {
  buildMemoryFromContact,
  buildMemoryFromTask,
  buildMemoryFromReminder,
  buildMemoryFromChat,
  searchMemoryGraph,
  retrieveMemoryContext,
  rebuildMemoryIndex,
  validateMemoryGraph,
  getMemoryGraphStats,
  extractRelationships,
  upsertMemoryNode,
  listMemoryNodes,
} from './memoryGraphApi'
export {
  ingestDocument,
  searchDocuments,
  chatWithDocument,
  listDocuments,
  deleteDocument,
  getDocumentStats,
  createDocumentFolder,
  listDocumentFolders,
  rebuildDocumentIndex,
} from './documentApi'
export {
  getProviderHealth,
  listCommunicationProviders,
  ingestCommunicationMessage,
  sendCommunicationMessage,
  syncCommunicationProvider,
  listConversationThreads,
  getConversationMessages,
  markThreadRead,
  archiveConversationThread,
  analyzeConversationThread,
  generateConversationSummary,
  generateAIReply,
  searchCommunications,
  getCommunicationStats,
  createCommunicationTemplate,
  listCommunicationTemplates,
  scheduleCommunicationMessage,
  listScheduledMessages,
} from './communicationApi'
export {
  getHealthProviderHealth,
  listHealthProviders,
  createPatient,
  getPatient,
  listPatients,
  addPatientVisit,
  addPatientAllergy,
  addPatientMedicalHistory,
  addPatientLabResult,
  createHealthFacility,
  listHealthFacilities,
  createHealthcareProvider,
  listHealthcareProviders,
  scheduleAppointment,
  rescheduleAppointment,
  cancelAppointment,
  completeAppointment,
  setAppointmentTravelTime,
  listAppointments,
  createRecurringAppointments,
  addMedication,
  updateMedicationStatus,
  listMedications,
  scheduleMedicationDose,
  recordMedicationDose,
  setMedicationRefillDate,
  scheduleVaccination,
  markVaccinationCompleted,
  listVaccinations,
  vaccinationDueList,
  registerDisease,
  listDiseases,
  registerHealthProgram,
  listHealthPrograms,
  generateDecisionSupport,
  getHealthStats,
  runHealthReminderChecks,
  listHealthSuggestions,
  dismissHealthSuggestion,
  generateFollowUpReminder,
  linkMedicalReport,
} from './healthApi'
export {
  getFinanceProviderHealth,
  listFinanceProviders,
  createBudget,
  getBudget,
  listBudgets,
  forecastBudget,
  recordExpense,
  getExpense,
  listExpenses,
  approveExpense,
  rejectExpense,
  markExpenseReimbursed,
  recordIncome,
  listIncome,
  createVendor,
  listVendors,
  searchVendors,
  evaluateVendor,
  createInvoice,
  listInvoices,
  markInvoicePaid,
  detectOverdueInvoices,
  linkInvoiceDocument,
  recordPayment,
  listPayments,
  createProcurementRequest,
  listProcurementRequests,
  addQuotation,
  compareQuotations,
  selectVendorForRequest,
  issuePurchaseOrder,
  recordGoodsReceipt,
  matchInvoiceToRequest,
  approveProcurementRequest,
  rejectProcurementRequest,
  registerAsset,
  listAssets,
  assignAsset,
  returnAsset,
  scheduleAssetMaintenance,
  checkAssetMaintenanceDue,
  disposeAsset,
  getFinanceStats,
  getFinanceMonthlyReport,
  getFinanceYearlyReport,
  runFinanceReminderChecks,
  listFinanceSuggestions,
  dismissFinanceSuggestion,
} from './financeApi'

export {
  approveRequest,
  bulkApproveRequests,
  bulkRejectRequests,
  cancelRequest,
  createApprovalRequest,
  delegateRequest,
  getApprovalMetrics,
  getApprovalPolicyBands,
  getApprovalRequest,
  getApprovalStats,
  listApprovalHistory,
  listApprovalRequests,
  listApprovalTemplates,
  listDelegatedApprovals,
  listExecutedApprovals,
  listExpiredApprovals,
  listPendingApprovals,
  listRejectedApprovals,
  listUrgentApprovals,
  rejectRequest,
  rollbackApprovalRequest,
  runApprovalScheduledChecks,
} from './delegationApi'

export {
  createMission,
  getMission,
  listMissions,
  updateMission,
  activateMission,
  pauseMission,
  abandonMission,
  listMissionTasks,
  addMissionTask,
  completeMissionTask,
  setMissionTaskStatus,
  requestMissionTaskApproval,
  getMissionTaskApprovalStatus,
  listMissionRecommendations,
  acceptMissionRecommendation,
  dismissMissionRecommendation,
  getMissionPredictions,
  getMissionLearningSnapshots,
  runMissionPlanningCycle,
  getMissionStats,
  listMissionHistory,
} from './missionControlApi'

export {
  createOrganization,
  getOrganization,
  updateOrganization,
  listMyOrganizations,
  createWorkspace,
  getWorkspace,
  listWorkspaces,
  listMembers,
  removeMember,
  changeMemberRole,
  inviteMember,
  listInvitations,
  acceptInvitation,
  revokeInvitation,
  listActivity,
  postAnnouncement,
  assignMissionToWorkspace,
  listSharedMissions,
  delegateTask,
  listSharedTasks,
  requestSharedApproval,
  getSharedTaskApprovalStatus,
  getOrganizationAnalytics,
} from './organizationApi'

export {
  createTenant,
  getTenant,
  listMyTenants,
  createIdentity,
  listIdentities,
  checkPermission,
  createRole,
  listRoles,
  assignRole,
  revokeRoleAssignment,
  createPolicy,
  updatePolicy,
  listPolicies,
  evaluatePolicy,
  createSession,
  refreshSession,
  revokeSession,
  listSessions,
  createGroup,
  listGroups,
  addGroupMember,
  removeGroupMember,
  assignRoleToGroup,
  createServiceAccount,
  listServiceAccounts,
  getDirectoryView,
  listAuditEvents,
  getSecurityAnalytics,
} from './securityApi'

export {
  publishSkill,
  updateSkill,
  submitSkillForReview,
  approveSkill,
  rejectSkill,
  installSkill,
  uninstallSkill,
  enableSkill,
  disableSkill,
  listInstalledSkills,
  grantSkillPermission,
  revokeSkillPermission,
  reviewSkill,
  listMarketplaceCatalog,
  getSkillDetail,
  getSkillAnalytics,
} from './marketplaceApi'

export {
  listAIProviders,
  listAIModels,
  testAIProvider,
  getAIUsage,
  updateModelPolicy,
  chatWithAriaGateway,
} from './aiGatewayApi'

export {
  listComputerCapabilities,
  planComputerAction,
  requestComputerApproval,
  registerLocalAgent,
  revokeLocalAgent,
  listLocalAgents,
  registerBrowserExtension,
  revokeBrowserExtension,
  listBrowserExtensions,
  logComputerActionResult,
  // Phase 5.6
  executeApprovedComputerAction,
  analyzeSelectedDocument,
  generateComputerActionSummary,
  getComputerAuditFeed,
  downloadGeneratedFileWithApproval,
} from './computerControlApi'
