"use strict";
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || (function () {
    var ownKeys = function(o) {
        ownKeys = Object.getOwnPropertyNames || function (o) {
            var ar = [];
            for (var k in o) if (Object.prototype.hasOwnProperty.call(o, k)) ar[ar.length] = k;
            return ar;
        };
        return ownKeys(o);
    };
    return function (mod) {
        if (mod && mod.__esModule) return mod;
        var result = {};
        if (mod != null) for (var k = ownKeys(mod), i = 0; i < k.length; i++) if (k[i] !== "default") __createBinding(result, mod, k[i]);
        __setModuleDefault(result, mod);
        return result;
    };
})();
Object.defineProperty(exports, "__esModule", { value: true });
exports.getCommunicationStats = exports.searchCommunications = exports.generateAIReply = exports.generateConversationSummary = exports.analyzeConversationThread = exports.archiveConversationThread = exports.markThreadRead = exports.getConversationMessages = exports.listConversationThreads = exports.syncCommunicationProvider = exports.sendCommunicationMessage = exports.ingestCommunicationMessage = exports.listCommunicationProviders = exports.getProviderHealth = exports.rebuildDocumentIndex = exports.listDocumentFolders = exports.createDocumentFolder = exports.getDocumentStats = exports.deleteDocument = exports.listDocuments = exports.chatWithDocument = exports.searchDocuments = exports.ingestDocument = exports.listMemoryNodes = exports.upsertMemoryNode = exports.extractRelationships = exports.getMemoryGraphStats = exports.validateMemoryGraph = exports.rebuildMemoryIndex = exports.retrieveMemoryContext = exports.searchMemoryGraph = exports.buildMemoryFromChat = exports.buildMemoryFromReminder = exports.buildMemoryFromTask = exports.buildMemoryFromContact = exports.getAgentStatus = exports.runAgentGraph = exports.setWorkflowEnabled = exports.getWorkflowSchedules = exports.listWorkflows = exports.getWorkflowHistory = exports.runWorkflow = exports.getPluginStatus = exports.generateDailyBriefing = exports.processDueReminders = exports.sendTestNotification = exports.executeAction = exports.synthesizeSpeech = exports.transcribeAudio = exports.chatWithAria = void 0;
exports.listBudgets = exports.getBudget = exports.createBudget = exports.listFinanceProviders = exports.getFinanceProviderHealth = exports.linkMedicalReport = exports.generateFollowUpReminder = exports.dismissHealthSuggestion = exports.listHealthSuggestions = exports.runHealthReminderChecks = exports.getHealthStats = exports.generateDecisionSupport = exports.listHealthPrograms = exports.registerHealthProgram = exports.listDiseases = exports.registerDisease = exports.vaccinationDueList = exports.listVaccinations = exports.markVaccinationCompleted = exports.scheduleVaccination = exports.setMedicationRefillDate = exports.recordMedicationDose = exports.scheduleMedicationDose = exports.listMedications = exports.updateMedicationStatus = exports.addMedication = exports.createRecurringAppointments = exports.listAppointments = exports.setAppointmentTravelTime = exports.completeAppointment = exports.cancelAppointment = exports.rescheduleAppointment = exports.scheduleAppointment = exports.listHealthcareProviders = exports.createHealthcareProvider = exports.listHealthFacilities = exports.createHealthFacility = exports.addPatientLabResult = exports.addPatientMedicalHistory = exports.addPatientAllergy = exports.addPatientVisit = exports.listPatients = exports.getPatient = exports.createPatient = exports.listHealthProviders = exports.getHealthProviderHealth = exports.listScheduledMessages = exports.scheduleCommunicationMessage = exports.listCommunicationTemplates = exports.createCommunicationTemplate = void 0;
exports.getApprovalMetrics = exports.delegateRequest = exports.createApprovalRequest = exports.cancelRequest = exports.bulkRejectRequests = exports.bulkApproveRequests = exports.approveRequest = exports.dismissFinanceSuggestion = exports.listFinanceSuggestions = exports.runFinanceReminderChecks = exports.getFinanceYearlyReport = exports.getFinanceMonthlyReport = exports.getFinanceStats = exports.disposeAsset = exports.checkAssetMaintenanceDue = exports.scheduleAssetMaintenance = exports.returnAsset = exports.assignAsset = exports.listAssets = exports.registerAsset = exports.rejectProcurementRequest = exports.approveProcurementRequest = exports.matchInvoiceToRequest = exports.recordGoodsReceipt = exports.issuePurchaseOrder = exports.selectVendorForRequest = exports.compareQuotations = exports.addQuotation = exports.listProcurementRequests = exports.createProcurementRequest = exports.listPayments = exports.recordPayment = exports.linkInvoiceDocument = exports.detectOverdueInvoices = exports.markInvoicePaid = exports.listInvoices = exports.createInvoice = exports.evaluateVendor = exports.searchVendors = exports.listVendors = exports.createVendor = exports.listIncome = exports.recordIncome = exports.markExpenseReimbursed = exports.rejectExpense = exports.approveExpense = exports.listExpenses = exports.getExpense = exports.recordExpense = exports.forecastBudget = void 0;
exports.revokeInvitation = exports.acceptInvitation = exports.listInvitations = exports.inviteMember = exports.changeMemberRole = exports.removeMember = exports.listMembers = exports.listWorkspaces = exports.getWorkspace = exports.createWorkspace = exports.listMyOrganizations = exports.updateOrganization = exports.getOrganization = exports.createOrganization = exports.listMissionHistory = exports.getMissionStats = exports.runMissionPlanningCycle = exports.getMissionLearningSnapshots = exports.getMissionPredictions = exports.dismissMissionRecommendation = exports.acceptMissionRecommendation = exports.listMissionRecommendations = exports.getMissionTaskApprovalStatus = exports.requestMissionTaskApproval = exports.setMissionTaskStatus = exports.completeMissionTask = exports.addMissionTask = exports.listMissionTasks = exports.abandonMission = exports.pauseMission = exports.activateMission = exports.updateMission = exports.listMissions = exports.getMission = exports.createMission = exports.runApprovalScheduledChecks = exports.rollbackApprovalRequest = exports.rejectRequest = exports.listUrgentApprovals = exports.listRejectedApprovals = exports.listPendingApprovals = exports.listExpiredApprovals = exports.listExecutedApprovals = exports.listDelegatedApprovals = exports.listApprovalTemplates = exports.listApprovalRequests = exports.listApprovalHistory = exports.getApprovalStats = exports.getApprovalRequest = exports.getApprovalPolicyBands = void 0;
exports.reviewSkill = exports.revokeSkillPermission = exports.grantSkillPermission = exports.listInstalledSkills = exports.disableSkill = exports.enableSkill = exports.uninstallSkill = exports.installSkill = exports.rejectSkill = exports.approveSkill = exports.submitSkillForReview = exports.updateSkill = exports.publishSkill = exports.getSecurityAnalytics = exports.listAuditEvents = exports.getDirectoryView = exports.listServiceAccounts = exports.createServiceAccount = exports.assignRoleToGroup = exports.removeGroupMember = exports.addGroupMember = exports.listGroups = exports.createGroup = exports.listSessions = exports.revokeSession = exports.refreshSession = exports.createSession = exports.evaluatePolicy = exports.listPolicies = exports.updatePolicy = exports.createPolicy = exports.revokeRoleAssignment = exports.assignRole = exports.listRoles = exports.createRole = exports.checkPermission = exports.listIdentities = exports.createIdentity = exports.listMyTenants = exports.getTenant = exports.createTenant = exports.getOrganizationAnalytics = exports.getSharedTaskApprovalStatus = exports.requestSharedApproval = exports.listSharedTasks = exports.delegateTask = exports.listSharedMissions = exports.assignMissionToWorkspace = exports.postAnnouncement = exports.listActivity = void 0;
exports.getMeetingSummary = exports.listMeetingSessions = exports.exportMeetingNotes = exports.approveMeetingFollowUp = exports.extractMeetingActionItems = exports.generateMeetingSummary = exports.addTranscriptChunk = exports.deleteMeetingSession = exports.endMeetingSession = exports.pauseMeetingSession = exports.startMeetingSession = exports.createMeetingSession = exports.downloadGeneratedFileWithApproval = exports.getComputerAuditFeed = exports.generateComputerActionSummary = exports.analyzeSelectedDocument = exports.executeApprovedComputerAction = exports.logComputerActionResult = exports.listBrowserExtensions = exports.revokeBrowserExtension = exports.registerBrowserExtension = exports.listLocalAgents = exports.revokeLocalAgent = exports.registerLocalAgent = exports.requestComputerApproval = exports.planComputerAction = exports.listComputerCapabilities = exports.chatWithAriaGateway = exports.updateModelPolicy = exports.getAIUsage = exports.testAIProvider = exports.listAIModels = exports.listAIProviders = exports.getSkillAnalytics = exports.getSkillDetail = exports.listMarketplaceCatalog = void 0;
const admin = __importStar(require("firebase-admin"));
// Initialize Firebase Admin once
admin.initializeApp();
var chat_1 = require("./chat");
Object.defineProperty(exports, "chatWithAria", { enumerable: true, get: function () { return chat_1.chatWithAria; } });
var voice_1 = require("./voice");
Object.defineProperty(exports, "transcribeAudio", { enumerable: true, get: function () { return voice_1.transcribeAudio; } });
Object.defineProperty(exports, "synthesizeSpeech", { enumerable: true, get: function () { return voice_1.synthesizeSpeech; } });
var executeAction_1 = require("./executeAction");
Object.defineProperty(exports, "executeAction", { enumerable: true, get: function () { return executeAction_1.executeAction; } });
var notifications_1 = require("./notifications");
Object.defineProperty(exports, "sendTestNotification", { enumerable: true, get: function () { return notifications_1.sendTestNotification; } });
var processDueReminders_1 = require("./processDueReminders");
Object.defineProperty(exports, "processDueReminders", { enumerable: true, get: function () { return processDueReminders_1.processDueReminders; } });
var briefing_1 = require("./briefing");
Object.defineProperty(exports, "generateDailyBriefing", { enumerable: true, get: function () { return briefing_1.generateDailyBriefing; } });
var pluginStatus_1 = require("./pluginStatus");
Object.defineProperty(exports, "getPluginStatus", { enumerable: true, get: function () { return pluginStatus_1.getPluginStatus; } });
var workflowApi_1 = require("./workflowApi");
Object.defineProperty(exports, "runWorkflow", { enumerable: true, get: function () { return workflowApi_1.runWorkflowFn; } });
Object.defineProperty(exports, "getWorkflowHistory", { enumerable: true, get: function () { return workflowApi_1.getWorkflowHistoryFn; } });
Object.defineProperty(exports, "listWorkflows", { enumerable: true, get: function () { return workflowApi_1.listWorkflowsFn; } });
Object.defineProperty(exports, "getWorkflowSchedules", { enumerable: true, get: function () { return workflowApi_1.getWorkflowSchedulesFn; } });
Object.defineProperty(exports, "setWorkflowEnabled", { enumerable: true, get: function () { return workflowApi_1.setWorkflowEnabledFn; } });
var agentApi_1 = require("./agentApi");
Object.defineProperty(exports, "runAgentGraph", { enumerable: true, get: function () { return agentApi_1.runAgentGraph; } });
Object.defineProperty(exports, "getAgentStatus", { enumerable: true, get: function () { return agentApi_1.getAgentStatus; } });
var memoryGraphApi_1 = require("./memoryGraphApi");
Object.defineProperty(exports, "buildMemoryFromContact", { enumerable: true, get: function () { return memoryGraphApi_1.buildMemoryFromContact; } });
Object.defineProperty(exports, "buildMemoryFromTask", { enumerable: true, get: function () { return memoryGraphApi_1.buildMemoryFromTask; } });
Object.defineProperty(exports, "buildMemoryFromReminder", { enumerable: true, get: function () { return memoryGraphApi_1.buildMemoryFromReminder; } });
Object.defineProperty(exports, "buildMemoryFromChat", { enumerable: true, get: function () { return memoryGraphApi_1.buildMemoryFromChat; } });
Object.defineProperty(exports, "searchMemoryGraph", { enumerable: true, get: function () { return memoryGraphApi_1.searchMemoryGraph; } });
Object.defineProperty(exports, "retrieveMemoryContext", { enumerable: true, get: function () { return memoryGraphApi_1.retrieveMemoryContext; } });
Object.defineProperty(exports, "rebuildMemoryIndex", { enumerable: true, get: function () { return memoryGraphApi_1.rebuildMemoryIndex; } });
Object.defineProperty(exports, "validateMemoryGraph", { enumerable: true, get: function () { return memoryGraphApi_1.validateMemoryGraph; } });
Object.defineProperty(exports, "getMemoryGraphStats", { enumerable: true, get: function () { return memoryGraphApi_1.getMemoryGraphStats; } });
Object.defineProperty(exports, "extractRelationships", { enumerable: true, get: function () { return memoryGraphApi_1.extractRelationships; } });
Object.defineProperty(exports, "upsertMemoryNode", { enumerable: true, get: function () { return memoryGraphApi_1.upsertMemoryNode; } });
Object.defineProperty(exports, "listMemoryNodes", { enumerable: true, get: function () { return memoryGraphApi_1.listMemoryNodes; } });
var documentApi_1 = require("./documentApi");
Object.defineProperty(exports, "ingestDocument", { enumerable: true, get: function () { return documentApi_1.ingestDocument; } });
Object.defineProperty(exports, "searchDocuments", { enumerable: true, get: function () { return documentApi_1.searchDocuments; } });
Object.defineProperty(exports, "chatWithDocument", { enumerable: true, get: function () { return documentApi_1.chatWithDocument; } });
Object.defineProperty(exports, "listDocuments", { enumerable: true, get: function () { return documentApi_1.listDocuments; } });
Object.defineProperty(exports, "deleteDocument", { enumerable: true, get: function () { return documentApi_1.deleteDocument; } });
Object.defineProperty(exports, "getDocumentStats", { enumerable: true, get: function () { return documentApi_1.getDocumentStats; } });
Object.defineProperty(exports, "createDocumentFolder", { enumerable: true, get: function () { return documentApi_1.createDocumentFolder; } });
Object.defineProperty(exports, "listDocumentFolders", { enumerable: true, get: function () { return documentApi_1.listDocumentFolders; } });
Object.defineProperty(exports, "rebuildDocumentIndex", { enumerable: true, get: function () { return documentApi_1.rebuildDocumentIndex; } });
var communicationApi_1 = require("./communicationApi");
Object.defineProperty(exports, "getProviderHealth", { enumerable: true, get: function () { return communicationApi_1.getProviderHealth; } });
Object.defineProperty(exports, "listCommunicationProviders", { enumerable: true, get: function () { return communicationApi_1.listCommunicationProviders; } });
Object.defineProperty(exports, "ingestCommunicationMessage", { enumerable: true, get: function () { return communicationApi_1.ingestCommunicationMessage; } });
Object.defineProperty(exports, "sendCommunicationMessage", { enumerable: true, get: function () { return communicationApi_1.sendCommunicationMessage; } });
Object.defineProperty(exports, "syncCommunicationProvider", { enumerable: true, get: function () { return communicationApi_1.syncCommunicationProvider; } });
Object.defineProperty(exports, "listConversationThreads", { enumerable: true, get: function () { return communicationApi_1.listConversationThreads; } });
Object.defineProperty(exports, "getConversationMessages", { enumerable: true, get: function () { return communicationApi_1.getConversationMessages; } });
Object.defineProperty(exports, "markThreadRead", { enumerable: true, get: function () { return communicationApi_1.markThreadRead; } });
Object.defineProperty(exports, "archiveConversationThread", { enumerable: true, get: function () { return communicationApi_1.archiveConversationThread; } });
Object.defineProperty(exports, "analyzeConversationThread", { enumerable: true, get: function () { return communicationApi_1.analyzeConversationThread; } });
Object.defineProperty(exports, "generateConversationSummary", { enumerable: true, get: function () { return communicationApi_1.generateConversationSummary; } });
Object.defineProperty(exports, "generateAIReply", { enumerable: true, get: function () { return communicationApi_1.generateAIReply; } });
Object.defineProperty(exports, "searchCommunications", { enumerable: true, get: function () { return communicationApi_1.searchCommunications; } });
Object.defineProperty(exports, "getCommunicationStats", { enumerable: true, get: function () { return communicationApi_1.getCommunicationStats; } });
Object.defineProperty(exports, "createCommunicationTemplate", { enumerable: true, get: function () { return communicationApi_1.createCommunicationTemplate; } });
Object.defineProperty(exports, "listCommunicationTemplates", { enumerable: true, get: function () { return communicationApi_1.listCommunicationTemplates; } });
Object.defineProperty(exports, "scheduleCommunicationMessage", { enumerable: true, get: function () { return communicationApi_1.scheduleCommunicationMessage; } });
Object.defineProperty(exports, "listScheduledMessages", { enumerable: true, get: function () { return communicationApi_1.listScheduledMessages; } });
var healthApi_1 = require("./healthApi");
Object.defineProperty(exports, "getHealthProviderHealth", { enumerable: true, get: function () { return healthApi_1.getHealthProviderHealth; } });
Object.defineProperty(exports, "listHealthProviders", { enumerable: true, get: function () { return healthApi_1.listHealthProviders; } });
Object.defineProperty(exports, "createPatient", { enumerable: true, get: function () { return healthApi_1.createPatient; } });
Object.defineProperty(exports, "getPatient", { enumerable: true, get: function () { return healthApi_1.getPatient; } });
Object.defineProperty(exports, "listPatients", { enumerable: true, get: function () { return healthApi_1.listPatients; } });
Object.defineProperty(exports, "addPatientVisit", { enumerable: true, get: function () { return healthApi_1.addPatientVisit; } });
Object.defineProperty(exports, "addPatientAllergy", { enumerable: true, get: function () { return healthApi_1.addPatientAllergy; } });
Object.defineProperty(exports, "addPatientMedicalHistory", { enumerable: true, get: function () { return healthApi_1.addPatientMedicalHistory; } });
Object.defineProperty(exports, "addPatientLabResult", { enumerable: true, get: function () { return healthApi_1.addPatientLabResult; } });
Object.defineProperty(exports, "createHealthFacility", { enumerable: true, get: function () { return healthApi_1.createHealthFacility; } });
Object.defineProperty(exports, "listHealthFacilities", { enumerable: true, get: function () { return healthApi_1.listHealthFacilities; } });
Object.defineProperty(exports, "createHealthcareProvider", { enumerable: true, get: function () { return healthApi_1.createHealthcareProvider; } });
Object.defineProperty(exports, "listHealthcareProviders", { enumerable: true, get: function () { return healthApi_1.listHealthcareProviders; } });
Object.defineProperty(exports, "scheduleAppointment", { enumerable: true, get: function () { return healthApi_1.scheduleAppointment; } });
Object.defineProperty(exports, "rescheduleAppointment", { enumerable: true, get: function () { return healthApi_1.rescheduleAppointment; } });
Object.defineProperty(exports, "cancelAppointment", { enumerable: true, get: function () { return healthApi_1.cancelAppointment; } });
Object.defineProperty(exports, "completeAppointment", { enumerable: true, get: function () { return healthApi_1.completeAppointment; } });
Object.defineProperty(exports, "setAppointmentTravelTime", { enumerable: true, get: function () { return healthApi_1.setAppointmentTravelTime; } });
Object.defineProperty(exports, "listAppointments", { enumerable: true, get: function () { return healthApi_1.listAppointments; } });
Object.defineProperty(exports, "createRecurringAppointments", { enumerable: true, get: function () { return healthApi_1.createRecurringAppointments; } });
Object.defineProperty(exports, "addMedication", { enumerable: true, get: function () { return healthApi_1.addMedication; } });
Object.defineProperty(exports, "updateMedicationStatus", { enumerable: true, get: function () { return healthApi_1.updateMedicationStatus; } });
Object.defineProperty(exports, "listMedications", { enumerable: true, get: function () { return healthApi_1.listMedications; } });
Object.defineProperty(exports, "scheduleMedicationDose", { enumerable: true, get: function () { return healthApi_1.scheduleMedicationDose; } });
Object.defineProperty(exports, "recordMedicationDose", { enumerable: true, get: function () { return healthApi_1.recordMedicationDose; } });
Object.defineProperty(exports, "setMedicationRefillDate", { enumerable: true, get: function () { return healthApi_1.setMedicationRefillDate; } });
Object.defineProperty(exports, "scheduleVaccination", { enumerable: true, get: function () { return healthApi_1.scheduleVaccination; } });
Object.defineProperty(exports, "markVaccinationCompleted", { enumerable: true, get: function () { return healthApi_1.markVaccinationCompleted; } });
Object.defineProperty(exports, "listVaccinations", { enumerable: true, get: function () { return healthApi_1.listVaccinations; } });
Object.defineProperty(exports, "vaccinationDueList", { enumerable: true, get: function () { return healthApi_1.vaccinationDueList; } });
Object.defineProperty(exports, "registerDisease", { enumerable: true, get: function () { return healthApi_1.registerDisease; } });
Object.defineProperty(exports, "listDiseases", { enumerable: true, get: function () { return healthApi_1.listDiseases; } });
Object.defineProperty(exports, "registerHealthProgram", { enumerable: true, get: function () { return healthApi_1.registerHealthProgram; } });
Object.defineProperty(exports, "listHealthPrograms", { enumerable: true, get: function () { return healthApi_1.listHealthPrograms; } });
Object.defineProperty(exports, "generateDecisionSupport", { enumerable: true, get: function () { return healthApi_1.generateDecisionSupport; } });
Object.defineProperty(exports, "getHealthStats", { enumerable: true, get: function () { return healthApi_1.getHealthStats; } });
Object.defineProperty(exports, "runHealthReminderChecks", { enumerable: true, get: function () { return healthApi_1.runHealthReminderChecks; } });
Object.defineProperty(exports, "listHealthSuggestions", { enumerable: true, get: function () { return healthApi_1.listHealthSuggestions; } });
Object.defineProperty(exports, "dismissHealthSuggestion", { enumerable: true, get: function () { return healthApi_1.dismissHealthSuggestion; } });
Object.defineProperty(exports, "generateFollowUpReminder", { enumerable: true, get: function () { return healthApi_1.generateFollowUpReminder; } });
Object.defineProperty(exports, "linkMedicalReport", { enumerable: true, get: function () { return healthApi_1.linkMedicalReport; } });
var financeApi_1 = require("./financeApi");
Object.defineProperty(exports, "getFinanceProviderHealth", { enumerable: true, get: function () { return financeApi_1.getFinanceProviderHealth; } });
Object.defineProperty(exports, "listFinanceProviders", { enumerable: true, get: function () { return financeApi_1.listFinanceProviders; } });
Object.defineProperty(exports, "createBudget", { enumerable: true, get: function () { return financeApi_1.createBudget; } });
Object.defineProperty(exports, "getBudget", { enumerable: true, get: function () { return financeApi_1.getBudget; } });
Object.defineProperty(exports, "listBudgets", { enumerable: true, get: function () { return financeApi_1.listBudgets; } });
Object.defineProperty(exports, "forecastBudget", { enumerable: true, get: function () { return financeApi_1.forecastBudget; } });
Object.defineProperty(exports, "recordExpense", { enumerable: true, get: function () { return financeApi_1.recordExpense; } });
Object.defineProperty(exports, "getExpense", { enumerable: true, get: function () { return financeApi_1.getExpense; } });
Object.defineProperty(exports, "listExpenses", { enumerable: true, get: function () { return financeApi_1.listExpenses; } });
Object.defineProperty(exports, "approveExpense", { enumerable: true, get: function () { return financeApi_1.approveExpense; } });
Object.defineProperty(exports, "rejectExpense", { enumerable: true, get: function () { return financeApi_1.rejectExpense; } });
Object.defineProperty(exports, "markExpenseReimbursed", { enumerable: true, get: function () { return financeApi_1.markExpenseReimbursed; } });
Object.defineProperty(exports, "recordIncome", { enumerable: true, get: function () { return financeApi_1.recordIncome; } });
Object.defineProperty(exports, "listIncome", { enumerable: true, get: function () { return financeApi_1.listIncome; } });
Object.defineProperty(exports, "createVendor", { enumerable: true, get: function () { return financeApi_1.createVendor; } });
Object.defineProperty(exports, "listVendors", { enumerable: true, get: function () { return financeApi_1.listVendors; } });
Object.defineProperty(exports, "searchVendors", { enumerable: true, get: function () { return financeApi_1.searchVendors; } });
Object.defineProperty(exports, "evaluateVendor", { enumerable: true, get: function () { return financeApi_1.evaluateVendor; } });
Object.defineProperty(exports, "createInvoice", { enumerable: true, get: function () { return financeApi_1.createInvoice; } });
Object.defineProperty(exports, "listInvoices", { enumerable: true, get: function () { return financeApi_1.listInvoices; } });
Object.defineProperty(exports, "markInvoicePaid", { enumerable: true, get: function () { return financeApi_1.markInvoicePaid; } });
Object.defineProperty(exports, "detectOverdueInvoices", { enumerable: true, get: function () { return financeApi_1.detectOverdueInvoices; } });
Object.defineProperty(exports, "linkInvoiceDocument", { enumerable: true, get: function () { return financeApi_1.linkInvoiceDocument; } });
Object.defineProperty(exports, "recordPayment", { enumerable: true, get: function () { return financeApi_1.recordPayment; } });
Object.defineProperty(exports, "listPayments", { enumerable: true, get: function () { return financeApi_1.listPayments; } });
Object.defineProperty(exports, "createProcurementRequest", { enumerable: true, get: function () { return financeApi_1.createProcurementRequest; } });
Object.defineProperty(exports, "listProcurementRequests", { enumerable: true, get: function () { return financeApi_1.listProcurementRequests; } });
Object.defineProperty(exports, "addQuotation", { enumerable: true, get: function () { return financeApi_1.addQuotation; } });
Object.defineProperty(exports, "compareQuotations", { enumerable: true, get: function () { return financeApi_1.compareQuotations; } });
Object.defineProperty(exports, "selectVendorForRequest", { enumerable: true, get: function () { return financeApi_1.selectVendorForRequest; } });
Object.defineProperty(exports, "issuePurchaseOrder", { enumerable: true, get: function () { return financeApi_1.issuePurchaseOrder; } });
Object.defineProperty(exports, "recordGoodsReceipt", { enumerable: true, get: function () { return financeApi_1.recordGoodsReceipt; } });
Object.defineProperty(exports, "matchInvoiceToRequest", { enumerable: true, get: function () { return financeApi_1.matchInvoiceToRequest; } });
Object.defineProperty(exports, "approveProcurementRequest", { enumerable: true, get: function () { return financeApi_1.approveProcurementRequest; } });
Object.defineProperty(exports, "rejectProcurementRequest", { enumerable: true, get: function () { return financeApi_1.rejectProcurementRequest; } });
Object.defineProperty(exports, "registerAsset", { enumerable: true, get: function () { return financeApi_1.registerAsset; } });
Object.defineProperty(exports, "listAssets", { enumerable: true, get: function () { return financeApi_1.listAssets; } });
Object.defineProperty(exports, "assignAsset", { enumerable: true, get: function () { return financeApi_1.assignAsset; } });
Object.defineProperty(exports, "returnAsset", { enumerable: true, get: function () { return financeApi_1.returnAsset; } });
Object.defineProperty(exports, "scheduleAssetMaintenance", { enumerable: true, get: function () { return financeApi_1.scheduleAssetMaintenance; } });
Object.defineProperty(exports, "checkAssetMaintenanceDue", { enumerable: true, get: function () { return financeApi_1.checkAssetMaintenanceDue; } });
Object.defineProperty(exports, "disposeAsset", { enumerable: true, get: function () { return financeApi_1.disposeAsset; } });
Object.defineProperty(exports, "getFinanceStats", { enumerable: true, get: function () { return financeApi_1.getFinanceStats; } });
Object.defineProperty(exports, "getFinanceMonthlyReport", { enumerable: true, get: function () { return financeApi_1.getFinanceMonthlyReport; } });
Object.defineProperty(exports, "getFinanceYearlyReport", { enumerable: true, get: function () { return financeApi_1.getFinanceYearlyReport; } });
Object.defineProperty(exports, "runFinanceReminderChecks", { enumerable: true, get: function () { return financeApi_1.runFinanceReminderChecks; } });
Object.defineProperty(exports, "listFinanceSuggestions", { enumerable: true, get: function () { return financeApi_1.listFinanceSuggestions; } });
Object.defineProperty(exports, "dismissFinanceSuggestion", { enumerable: true, get: function () { return financeApi_1.dismissFinanceSuggestion; } });
var delegationApi_1 = require("./delegationApi");
Object.defineProperty(exports, "approveRequest", { enumerable: true, get: function () { return delegationApi_1.approveRequest; } });
Object.defineProperty(exports, "bulkApproveRequests", { enumerable: true, get: function () { return delegationApi_1.bulkApproveRequests; } });
Object.defineProperty(exports, "bulkRejectRequests", { enumerable: true, get: function () { return delegationApi_1.bulkRejectRequests; } });
Object.defineProperty(exports, "cancelRequest", { enumerable: true, get: function () { return delegationApi_1.cancelRequest; } });
Object.defineProperty(exports, "createApprovalRequest", { enumerable: true, get: function () { return delegationApi_1.createApprovalRequest; } });
Object.defineProperty(exports, "delegateRequest", { enumerable: true, get: function () { return delegationApi_1.delegateRequest; } });
Object.defineProperty(exports, "getApprovalMetrics", { enumerable: true, get: function () { return delegationApi_1.getApprovalMetrics; } });
Object.defineProperty(exports, "getApprovalPolicyBands", { enumerable: true, get: function () { return delegationApi_1.getApprovalPolicyBands; } });
Object.defineProperty(exports, "getApprovalRequest", { enumerable: true, get: function () { return delegationApi_1.getApprovalRequest; } });
Object.defineProperty(exports, "getApprovalStats", { enumerable: true, get: function () { return delegationApi_1.getApprovalStats; } });
Object.defineProperty(exports, "listApprovalHistory", { enumerable: true, get: function () { return delegationApi_1.listApprovalHistory; } });
Object.defineProperty(exports, "listApprovalRequests", { enumerable: true, get: function () { return delegationApi_1.listApprovalRequests; } });
Object.defineProperty(exports, "listApprovalTemplates", { enumerable: true, get: function () { return delegationApi_1.listApprovalTemplates; } });
Object.defineProperty(exports, "listDelegatedApprovals", { enumerable: true, get: function () { return delegationApi_1.listDelegatedApprovals; } });
Object.defineProperty(exports, "listExecutedApprovals", { enumerable: true, get: function () { return delegationApi_1.listExecutedApprovals; } });
Object.defineProperty(exports, "listExpiredApprovals", { enumerable: true, get: function () { return delegationApi_1.listExpiredApprovals; } });
Object.defineProperty(exports, "listPendingApprovals", { enumerable: true, get: function () { return delegationApi_1.listPendingApprovals; } });
Object.defineProperty(exports, "listRejectedApprovals", { enumerable: true, get: function () { return delegationApi_1.listRejectedApprovals; } });
Object.defineProperty(exports, "listUrgentApprovals", { enumerable: true, get: function () { return delegationApi_1.listUrgentApprovals; } });
Object.defineProperty(exports, "rejectRequest", { enumerable: true, get: function () { return delegationApi_1.rejectRequest; } });
Object.defineProperty(exports, "rollbackApprovalRequest", { enumerable: true, get: function () { return delegationApi_1.rollbackApprovalRequest; } });
Object.defineProperty(exports, "runApprovalScheduledChecks", { enumerable: true, get: function () { return delegationApi_1.runApprovalScheduledChecks; } });
var missionControlApi_1 = require("./missionControlApi");
Object.defineProperty(exports, "createMission", { enumerable: true, get: function () { return missionControlApi_1.createMission; } });
Object.defineProperty(exports, "getMission", { enumerable: true, get: function () { return missionControlApi_1.getMission; } });
Object.defineProperty(exports, "listMissions", { enumerable: true, get: function () { return missionControlApi_1.listMissions; } });
Object.defineProperty(exports, "updateMission", { enumerable: true, get: function () { return missionControlApi_1.updateMission; } });
Object.defineProperty(exports, "activateMission", { enumerable: true, get: function () { return missionControlApi_1.activateMission; } });
Object.defineProperty(exports, "pauseMission", { enumerable: true, get: function () { return missionControlApi_1.pauseMission; } });
Object.defineProperty(exports, "abandonMission", { enumerable: true, get: function () { return missionControlApi_1.abandonMission; } });
Object.defineProperty(exports, "listMissionTasks", { enumerable: true, get: function () { return missionControlApi_1.listMissionTasks; } });
Object.defineProperty(exports, "addMissionTask", { enumerable: true, get: function () { return missionControlApi_1.addMissionTask; } });
Object.defineProperty(exports, "completeMissionTask", { enumerable: true, get: function () { return missionControlApi_1.completeMissionTask; } });
Object.defineProperty(exports, "setMissionTaskStatus", { enumerable: true, get: function () { return missionControlApi_1.setMissionTaskStatus; } });
Object.defineProperty(exports, "requestMissionTaskApproval", { enumerable: true, get: function () { return missionControlApi_1.requestMissionTaskApproval; } });
Object.defineProperty(exports, "getMissionTaskApprovalStatus", { enumerable: true, get: function () { return missionControlApi_1.getMissionTaskApprovalStatus; } });
Object.defineProperty(exports, "listMissionRecommendations", { enumerable: true, get: function () { return missionControlApi_1.listMissionRecommendations; } });
Object.defineProperty(exports, "acceptMissionRecommendation", { enumerable: true, get: function () { return missionControlApi_1.acceptMissionRecommendation; } });
Object.defineProperty(exports, "dismissMissionRecommendation", { enumerable: true, get: function () { return missionControlApi_1.dismissMissionRecommendation; } });
Object.defineProperty(exports, "getMissionPredictions", { enumerable: true, get: function () { return missionControlApi_1.getMissionPredictions; } });
Object.defineProperty(exports, "getMissionLearningSnapshots", { enumerable: true, get: function () { return missionControlApi_1.getMissionLearningSnapshots; } });
Object.defineProperty(exports, "runMissionPlanningCycle", { enumerable: true, get: function () { return missionControlApi_1.runMissionPlanningCycle; } });
Object.defineProperty(exports, "getMissionStats", { enumerable: true, get: function () { return missionControlApi_1.getMissionStats; } });
Object.defineProperty(exports, "listMissionHistory", { enumerable: true, get: function () { return missionControlApi_1.listMissionHistory; } });
var organizationApi_1 = require("./organizationApi");
Object.defineProperty(exports, "createOrganization", { enumerable: true, get: function () { return organizationApi_1.createOrganization; } });
Object.defineProperty(exports, "getOrganization", { enumerable: true, get: function () { return organizationApi_1.getOrganization; } });
Object.defineProperty(exports, "updateOrganization", { enumerable: true, get: function () { return organizationApi_1.updateOrganization; } });
Object.defineProperty(exports, "listMyOrganizations", { enumerable: true, get: function () { return organizationApi_1.listMyOrganizations; } });
Object.defineProperty(exports, "createWorkspace", { enumerable: true, get: function () { return organizationApi_1.createWorkspace; } });
Object.defineProperty(exports, "getWorkspace", { enumerable: true, get: function () { return organizationApi_1.getWorkspace; } });
Object.defineProperty(exports, "listWorkspaces", { enumerable: true, get: function () { return organizationApi_1.listWorkspaces; } });
Object.defineProperty(exports, "listMembers", { enumerable: true, get: function () { return organizationApi_1.listMembers; } });
Object.defineProperty(exports, "removeMember", { enumerable: true, get: function () { return organizationApi_1.removeMember; } });
Object.defineProperty(exports, "changeMemberRole", { enumerable: true, get: function () { return organizationApi_1.changeMemberRole; } });
Object.defineProperty(exports, "inviteMember", { enumerable: true, get: function () { return organizationApi_1.inviteMember; } });
Object.defineProperty(exports, "listInvitations", { enumerable: true, get: function () { return organizationApi_1.listInvitations; } });
Object.defineProperty(exports, "acceptInvitation", { enumerable: true, get: function () { return organizationApi_1.acceptInvitation; } });
Object.defineProperty(exports, "revokeInvitation", { enumerable: true, get: function () { return organizationApi_1.revokeInvitation; } });
Object.defineProperty(exports, "listActivity", { enumerable: true, get: function () { return organizationApi_1.listActivity; } });
Object.defineProperty(exports, "postAnnouncement", { enumerable: true, get: function () { return organizationApi_1.postAnnouncement; } });
Object.defineProperty(exports, "assignMissionToWorkspace", { enumerable: true, get: function () { return organizationApi_1.assignMissionToWorkspace; } });
Object.defineProperty(exports, "listSharedMissions", { enumerable: true, get: function () { return organizationApi_1.listSharedMissions; } });
Object.defineProperty(exports, "delegateTask", { enumerable: true, get: function () { return organizationApi_1.delegateTask; } });
Object.defineProperty(exports, "listSharedTasks", { enumerable: true, get: function () { return organizationApi_1.listSharedTasks; } });
Object.defineProperty(exports, "requestSharedApproval", { enumerable: true, get: function () { return organizationApi_1.requestSharedApproval; } });
Object.defineProperty(exports, "getSharedTaskApprovalStatus", { enumerable: true, get: function () { return organizationApi_1.getSharedTaskApprovalStatus; } });
Object.defineProperty(exports, "getOrganizationAnalytics", { enumerable: true, get: function () { return organizationApi_1.getOrganizationAnalytics; } });
var securityApi_1 = require("./securityApi");
Object.defineProperty(exports, "createTenant", { enumerable: true, get: function () { return securityApi_1.createTenant; } });
Object.defineProperty(exports, "getTenant", { enumerable: true, get: function () { return securityApi_1.getTenant; } });
Object.defineProperty(exports, "listMyTenants", { enumerable: true, get: function () { return securityApi_1.listMyTenants; } });
Object.defineProperty(exports, "createIdentity", { enumerable: true, get: function () { return securityApi_1.createIdentity; } });
Object.defineProperty(exports, "listIdentities", { enumerable: true, get: function () { return securityApi_1.listIdentities; } });
Object.defineProperty(exports, "checkPermission", { enumerable: true, get: function () { return securityApi_1.checkPermission; } });
Object.defineProperty(exports, "createRole", { enumerable: true, get: function () { return securityApi_1.createRole; } });
Object.defineProperty(exports, "listRoles", { enumerable: true, get: function () { return securityApi_1.listRoles; } });
Object.defineProperty(exports, "assignRole", { enumerable: true, get: function () { return securityApi_1.assignRole; } });
Object.defineProperty(exports, "revokeRoleAssignment", { enumerable: true, get: function () { return securityApi_1.revokeRoleAssignment; } });
Object.defineProperty(exports, "createPolicy", { enumerable: true, get: function () { return securityApi_1.createPolicy; } });
Object.defineProperty(exports, "updatePolicy", { enumerable: true, get: function () { return securityApi_1.updatePolicy; } });
Object.defineProperty(exports, "listPolicies", { enumerable: true, get: function () { return securityApi_1.listPolicies; } });
Object.defineProperty(exports, "evaluatePolicy", { enumerable: true, get: function () { return securityApi_1.evaluatePolicy; } });
Object.defineProperty(exports, "createSession", { enumerable: true, get: function () { return securityApi_1.createSession; } });
Object.defineProperty(exports, "refreshSession", { enumerable: true, get: function () { return securityApi_1.refreshSession; } });
Object.defineProperty(exports, "revokeSession", { enumerable: true, get: function () { return securityApi_1.revokeSession; } });
Object.defineProperty(exports, "listSessions", { enumerable: true, get: function () { return securityApi_1.listSessions; } });
Object.defineProperty(exports, "createGroup", { enumerable: true, get: function () { return securityApi_1.createGroup; } });
Object.defineProperty(exports, "listGroups", { enumerable: true, get: function () { return securityApi_1.listGroups; } });
Object.defineProperty(exports, "addGroupMember", { enumerable: true, get: function () { return securityApi_1.addGroupMember; } });
Object.defineProperty(exports, "removeGroupMember", { enumerable: true, get: function () { return securityApi_1.removeGroupMember; } });
Object.defineProperty(exports, "assignRoleToGroup", { enumerable: true, get: function () { return securityApi_1.assignRoleToGroup; } });
Object.defineProperty(exports, "createServiceAccount", { enumerable: true, get: function () { return securityApi_1.createServiceAccount; } });
Object.defineProperty(exports, "listServiceAccounts", { enumerable: true, get: function () { return securityApi_1.listServiceAccounts; } });
Object.defineProperty(exports, "getDirectoryView", { enumerable: true, get: function () { return securityApi_1.getDirectoryView; } });
Object.defineProperty(exports, "listAuditEvents", { enumerable: true, get: function () { return securityApi_1.listAuditEvents; } });
Object.defineProperty(exports, "getSecurityAnalytics", { enumerable: true, get: function () { return securityApi_1.getSecurityAnalytics; } });
var marketplaceApi_1 = require("./marketplaceApi");
Object.defineProperty(exports, "publishSkill", { enumerable: true, get: function () { return marketplaceApi_1.publishSkill; } });
Object.defineProperty(exports, "updateSkill", { enumerable: true, get: function () { return marketplaceApi_1.updateSkill; } });
Object.defineProperty(exports, "submitSkillForReview", { enumerable: true, get: function () { return marketplaceApi_1.submitSkillForReview; } });
Object.defineProperty(exports, "approveSkill", { enumerable: true, get: function () { return marketplaceApi_1.approveSkill; } });
Object.defineProperty(exports, "rejectSkill", { enumerable: true, get: function () { return marketplaceApi_1.rejectSkill; } });
Object.defineProperty(exports, "installSkill", { enumerable: true, get: function () { return marketplaceApi_1.installSkill; } });
Object.defineProperty(exports, "uninstallSkill", { enumerable: true, get: function () { return marketplaceApi_1.uninstallSkill; } });
Object.defineProperty(exports, "enableSkill", { enumerable: true, get: function () { return marketplaceApi_1.enableSkill; } });
Object.defineProperty(exports, "disableSkill", { enumerable: true, get: function () { return marketplaceApi_1.disableSkill; } });
Object.defineProperty(exports, "listInstalledSkills", { enumerable: true, get: function () { return marketplaceApi_1.listInstalledSkills; } });
Object.defineProperty(exports, "grantSkillPermission", { enumerable: true, get: function () { return marketplaceApi_1.grantSkillPermission; } });
Object.defineProperty(exports, "revokeSkillPermission", { enumerable: true, get: function () { return marketplaceApi_1.revokeSkillPermission; } });
Object.defineProperty(exports, "reviewSkill", { enumerable: true, get: function () { return marketplaceApi_1.reviewSkill; } });
Object.defineProperty(exports, "listMarketplaceCatalog", { enumerable: true, get: function () { return marketplaceApi_1.listMarketplaceCatalog; } });
Object.defineProperty(exports, "getSkillDetail", { enumerable: true, get: function () { return marketplaceApi_1.getSkillDetail; } });
Object.defineProperty(exports, "getSkillAnalytics", { enumerable: true, get: function () { return marketplaceApi_1.getSkillAnalytics; } });
var aiGatewayApi_1 = require("./aiGatewayApi");
Object.defineProperty(exports, "listAIProviders", { enumerable: true, get: function () { return aiGatewayApi_1.listAIProviders; } });
Object.defineProperty(exports, "listAIModels", { enumerable: true, get: function () { return aiGatewayApi_1.listAIModels; } });
Object.defineProperty(exports, "testAIProvider", { enumerable: true, get: function () { return aiGatewayApi_1.testAIProvider; } });
Object.defineProperty(exports, "getAIUsage", { enumerable: true, get: function () { return aiGatewayApi_1.getAIUsage; } });
Object.defineProperty(exports, "updateModelPolicy", { enumerable: true, get: function () { return aiGatewayApi_1.updateModelPolicy; } });
Object.defineProperty(exports, "chatWithAriaGateway", { enumerable: true, get: function () { return aiGatewayApi_1.chatWithAriaGateway; } });
var computerControlApi_1 = require("./computerControlApi");
Object.defineProperty(exports, "listComputerCapabilities", { enumerable: true, get: function () { return computerControlApi_1.listComputerCapabilities; } });
Object.defineProperty(exports, "planComputerAction", { enumerable: true, get: function () { return computerControlApi_1.planComputerAction; } });
Object.defineProperty(exports, "requestComputerApproval", { enumerable: true, get: function () { return computerControlApi_1.requestComputerApproval; } });
Object.defineProperty(exports, "registerLocalAgent", { enumerable: true, get: function () { return computerControlApi_1.registerLocalAgent; } });
Object.defineProperty(exports, "revokeLocalAgent", { enumerable: true, get: function () { return computerControlApi_1.revokeLocalAgent; } });
Object.defineProperty(exports, "listLocalAgents", { enumerable: true, get: function () { return computerControlApi_1.listLocalAgents; } });
Object.defineProperty(exports, "registerBrowserExtension", { enumerable: true, get: function () { return computerControlApi_1.registerBrowserExtension; } });
Object.defineProperty(exports, "revokeBrowserExtension", { enumerable: true, get: function () { return computerControlApi_1.revokeBrowserExtension; } });
Object.defineProperty(exports, "listBrowserExtensions", { enumerable: true, get: function () { return computerControlApi_1.listBrowserExtensions; } });
Object.defineProperty(exports, "logComputerActionResult", { enumerable: true, get: function () { return computerControlApi_1.logComputerActionResult; } });
// Phase 5.6
Object.defineProperty(exports, "executeApprovedComputerAction", { enumerable: true, get: function () { return computerControlApi_1.executeApprovedComputerAction; } });
Object.defineProperty(exports, "analyzeSelectedDocument", { enumerable: true, get: function () { return computerControlApi_1.analyzeSelectedDocument; } });
Object.defineProperty(exports, "generateComputerActionSummary", { enumerable: true, get: function () { return computerControlApi_1.generateComputerActionSummary; } });
Object.defineProperty(exports, "getComputerAuditFeed", { enumerable: true, get: function () { return computerControlApi_1.getComputerAuditFeed; } });
Object.defineProperty(exports, "downloadGeneratedFileWithApproval", { enumerable: true, get: function () { return computerControlApi_1.downloadGeneratedFileWithApproval; } });
// Phase 5.7 — Meeting Agent
var meetingAgentApi_1 = require("./meetingAgentApi");
Object.defineProperty(exports, "createMeetingSession", { enumerable: true, get: function () { return meetingAgentApi_1.createMeetingSession; } });
Object.defineProperty(exports, "startMeetingSession", { enumerable: true, get: function () { return meetingAgentApi_1.startMeetingSession; } });
Object.defineProperty(exports, "pauseMeetingSession", { enumerable: true, get: function () { return meetingAgentApi_1.pauseMeetingSession; } });
Object.defineProperty(exports, "endMeetingSession", { enumerable: true, get: function () { return meetingAgentApi_1.endMeetingSession; } });
Object.defineProperty(exports, "deleteMeetingSession", { enumerable: true, get: function () { return meetingAgentApi_1.deleteMeetingSession; } });
Object.defineProperty(exports, "addTranscriptChunk", { enumerable: true, get: function () { return meetingAgentApi_1.addTranscriptChunk; } });
Object.defineProperty(exports, "generateMeetingSummary", { enumerable: true, get: function () { return meetingAgentApi_1.generateMeetingSummary; } });
Object.defineProperty(exports, "extractMeetingActionItems", { enumerable: true, get: function () { return meetingAgentApi_1.extractMeetingActionItems; } });
Object.defineProperty(exports, "approveMeetingFollowUp", { enumerable: true, get: function () { return meetingAgentApi_1.approveMeetingFollowUp; } });
Object.defineProperty(exports, "exportMeetingNotes", { enumerable: true, get: function () { return meetingAgentApi_1.exportMeetingNotes; } });
Object.defineProperty(exports, "listMeetingSessions", { enumerable: true, get: function () { return meetingAgentApi_1.listMeetingSessions; } });
Object.defineProperty(exports, "getMeetingSummary", { enumerable: true, get: function () { return meetingAgentApi_1.getMeetingSummary; } });
//# sourceMappingURL=index.js.map