"use strict";
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || (function () {
    var ownKeys = function(o) {
        ownKeys = Object.getOwnPropertyNames || function (o) {
            var ar = [];
            for (var k in o) if (Object.prototype.hasOwnProperty.call(o, k)) ar[ar.length] = k;
            return ar;
        };
        return ownKeys(o);
    };
    return function (mod) {
        if (mod && mod.__esModule) return mod;
        var result = {};
        if (mod != null) for (var k = ownKeys(mod), i = 0; i < k.length; i++) if (k[i] !== "default") __createBinding(result, mod, k[i]);
        __setModuleDefault(result, mod);
        return result;
    };
})();
Object.defineProperty(exports, "__esModule", { value: true });
exports.getCommunicationStats = exports.searchCommunications = exports.generateAIReply = exports.generateConversationSummary = exports.analyzeConversationThread = exports.archiveConversationThread = exports.markThreadRead = exports.getConversationMessages = exports.listConversationThreads = exports.syncCommunicationProvider = exports.sendCommunicationMessage = exports.ingestCommunicationMessage = exports.listCommunicationProviders = exports.getProviderHealth = exports.rebuildDocumentIndex = exports.listDocumentFolders = exports.createDocumentFolder = exports.getDocumentStats = exports.deleteDocument = exports.listDocuments = exports.chatWithDocument = exports.searchDocuments = exports.ingestDocument = exports.listMemoryNodes = exports.upsertMemoryNode = exports.extractRelationships = exports.getMemoryGraphStats = exports.validateMemoryGraph = exports.rebuildMemoryIndex = exports.retrieveMemoryContext = exports.searchMemoryGraph = exports.buildMemoryFromChat = exports.buildMemoryFromReminder = exports.buildMemoryFromTask = exports.buildMemoryFromContact = exports.getAgentStatus = exports.runAgentGraph = exports.setWorkflowEnabled = exports.getWorkflowSchedules = exports.listWorkflows = exports.getWorkflowHistory = exports.runWorkflow = exports.getPluginStatus = exports.generateDailyBriefing = exports.processDueReminders = exports.sendTestNotification = exports.executeAction = exports.synthesizeSpeech = exports.transcribeAudio = exports.chatWithAria = void 0;
exports.listBudgets = exports.getBudget = exports.createBudget = exports.listFinanceProviders = exports.getFinanceProviderHealth = exports.linkMedicalReport = exports.generateFollowUpReminder = exports.dismissHealthSuggestion = exports.listHealthSuggestions = exports.runHealthReminderChecks = exports.getHealthStats = exports.generateDecisionSupport = exports.listHealthPrograms = exports.registerHealthProgram = exports.listDiseases = exports.registerDisease = exports.vaccinationDueList = exports.listVaccinations = exports.markVaccinationCompleted = exports.scheduleVaccination = exports.setMedicationRefillDate = exports.recordMedicationDose = exports.scheduleMedicationDose = exports.listMedications = exports.updateMedicationStatus = exports.addMedication = exports.createRecurringAppointments = exports.listAppointments = exports.setAppointmentTravelTime = exports.completeAppointment = exports.cancelAppointment = exports.rescheduleAppointment = exports.scheduleAppointment = exports.listHealthcareProviders = exports.createHealthcareProvider = exports.listHealthFacilities = exports.createHealthFacility = exports.addPatientLabResult = exports.addPatientMedicalHistory = exports.addPatientAllergy = exports.addPatientVisit = exports.listPatients = exports.getPatient = exports.createPatient = exports.listHealthProviders = exports.getHealthProviderHealth = exports.listScheduledMessages = exports.scheduleCommunicationMessage = exports.listCommunicationTemplates = exports.createCommunicationTemplate = void 0;
exports.getApprovalMetrics = exports.delegateRequest = exports.createApprovalRequest = exports.cancelRequest = exports.bulkRejectRequests = exports.bulkApproveRequests = exports.approveRequest = exports.dismissFinanceSuggestion = exports.listFinanceSuggestions = exports.runFinanceReminderChecks = exports.getFinanceYearlyReport = exports.getFinanceMonthlyReport = exports.getFinanceStats = exports.disposeAsset = exports.checkAssetMaintenanceDue = exports.scheduleAssetMaintenance = exports.returnAsset = exports.assignAsset = exports.listAssets = exports.registerAsset = exports.rejectProcurementRequest = exports.approveProcurementRequest = exports.matchInvoiceToRequest = exports.recordGoodsReceipt = exports.issuePurchaseOrder = exports.selectVendorForRequest = exports.compareQuotations = exports.addQuotation = exports.listProcurementRequests = exports.createProcurementRequest = exports.listPayments = exports.recordPayment = exports.linkInvoiceDocument = exports.detectOverdueInvoices = exports.markInvoicePaid = exports.listInvoices = exports.createInvoice = exports.evaluateVendor = exports.searchVendors = exports.listVendors = exports.createVendor = exports.listIncome = exports.recordIncome = exports.markExpenseReimbursed = exports.rejectExpense = exports.approveExpense = exports.listExpenses = exports.getExpense = exports.recordExpense = exports.forecastBudget = void 0;
exports.runApprovalScheduledChecks = exports.rollbackApprovalRequest = exports.rejectRequest = exports.listUrgentApprovals = exports.listRejectedApprovals = exports.listPendingApprovals = exports.listExpiredApprovals = exports.listExecutedApprovals = exports.listDelegatedApprovals = exports.listApprovalTemplates = exports.listApprovalRequests = exports.listApprovalHistory = exports.getApprovalStats = exports.getApprovalRequest = exports.getApprovalPolicyBands = void 0;
const admin = __importStar(require("firebase-admin"));
// Initialize Firebase Admin once
admin.initializeApp();
var chat_1 = require("./chat");
Object.defineProperty(exports, "chatWithAria", { enumerable: true, get: function () { return chat_1.chatWithAria; } });
var voice_1 = require("./voice");
Object.defineProperty(exports, "transcribeAudio", { enumerable: true, get: function () { return voice_1.transcribeAudio; } });
Object.defineProperty(exports, "synthesizeSpeech", { enumerable: true, get: function () { return voice_1.synthesizeSpeech; } });
var executeAction_1 = require("./executeAction");
Object.defineProperty(exports, "executeAction", { enumerable: true, get: function () { return executeAction_1.executeAction; } });
var notifications_1 = require("./notifications");
Object.defineProperty(exports, "sendTestNotification", { enumerable: true, get: function () { return notifications_1.sendTestNotification; } });
var processDueReminders_1 = require("./processDueReminders");
Object.defineProperty(exports, "processDueReminders", { enumerable: true, get: function () { return processDueReminders_1.processDueReminders; } });
var briefing_1 = require("./briefing");
Object.defineProperty(exports, "generateDailyBriefing", { enumerable: true, get: function () { return briefing_1.generateDailyBriefing; } });
var pluginStatus_1 = require("./pluginStatus");
Object.defineProperty(exports, "getPluginStatus", { enumerable: true, get: function () { return pluginStatus_1.getPluginStatus; } });
var workflowApi_1 = require("./workflowApi");
Object.defineProperty(exports, "runWorkflow", { enumerable: true, get: function () { return workflowApi_1.runWorkflowFn; } });
Object.defineProperty(exports, "getWorkflowHistory", { enumerable: true, get: function () { return workflowApi_1.getWorkflowHistoryFn; } });
Object.defineProperty(exports, "listWorkflows", { enumerable: true, get: function () { return workflowApi_1.listWorkflowsFn; } });
Object.defineProperty(exports, "getWorkflowSchedules", { enumerable: true, get: function () { return workflowApi_1.getWorkflowSchedulesFn; } });
Object.defineProperty(exports, "setWorkflowEnabled", { enumerable: true, get: function () { return workflowApi_1.setWorkflowEnabledFn; } });
var agentApi_1 = require("./agentApi");
Object.defineProperty(exports, "runAgentGraph", { enumerable: true, get: function () { return agentApi_1.runAgentGraph; } });
Object.defineProperty(exports, "getAgentStatus", { enumerable: true, get: function () { return agentApi_1.getAgentStatus; } });
var memoryGraphApi_1 = require("./memoryGraphApi");
Object.defineProperty(exports, "buildMemoryFromContact", { enumerable: true, get: function () { return memoryGraphApi_1.buildMemoryFromContact; } });
Object.defineProperty(exports, "buildMemoryFromTask", { enumerable: true, get: function () { return memoryGraphApi_1.buildMemoryFromTask; } });
Object.defineProperty(exports, "buildMemoryFromReminder", { enumerable: true, get: function () { return memoryGraphApi_1.buildMemoryFromReminder; } });
Object.defineProperty(exports, "buildMemoryFromChat", { enumerable: true, get: function () { return memoryGraphApi_1.buildMemoryFromChat; } });
Object.defineProperty(exports, "searchMemoryGraph", { enumerable: true, get: function () { return memoryGraphApi_1.searchMemoryGraph; } });
Object.defineProperty(exports, "retrieveMemoryContext", { enumerable: true, get: function () { return memoryGraphApi_1.retrieveMemoryContext; } });
Object.defineProperty(exports, "rebuildMemoryIndex", { enumerable: true, get: function () { return memoryGraphApi_1.rebuildMemoryIndex; } });
Object.defineProperty(exports, "validateMemoryGraph", { enumerable: true, get: function () { return memoryGraphApi_1.validateMemoryGraph; } });
Object.defineProperty(exports, "getMemoryGraphStats", { enumerable: true, get: function () { return memoryGraphApi_1.getMemoryGraphStats; } });
Object.defineProperty(exports, "extractRelationships", { enumerable: true, get: function () { return memoryGraphApi_1.extractRelationships; } });
Object.defineProperty(exports, "upsertMemoryNode", { enumerable: true, get: function () { return memoryGraphApi_1.upsertMemoryNode; } });
Object.defineProperty(exports, "listMemoryNodes", { enumerable: true, get: function () { return memoryGraphApi_1.listMemoryNodes; } });
var documentApi_1 = require("./documentApi");
Object.defineProperty(exports, "ingestDocument", { enumerable: true, get: function () { return documentApi_1.ingestDocument; } });
Object.defineProperty(exports, "searchDocuments", { enumerable: true, get: function () { return documentApi_1.searchDocuments; } });
Object.defineProperty(exports, "chatWithDocument", { enumerable: true, get: function () { return documentApi_1.chatWithDocument; } });
Object.defineProperty(exports, "listDocuments", { enumerable: true, get: function () { return documentApi_1.listDocuments; } });
Object.defineProperty(exports, "deleteDocument", { enumerable: true, get: function () { return documentApi_1.deleteDocument; } });
Object.defineProperty(exports, "getDocumentStats", { enumerable: true, get: function () { return documentApi_1.getDocumentStats; } });
Object.defineProperty(exports, "createDocumentFolder", { enumerable: true, get: function () { return documentApi_1.createDocumentFolder; } });
Object.defineProperty(exports, "listDocumentFolders", { enumerable: true, get: function () { return documentApi_1.listDocumentFolders; } });
Object.defineProperty(exports, "rebuildDocumentIndex", { enumerable: true, get: function () { return documentApi_1.rebuildDocumentIndex; } });
var communicationApi_1 = require("./communicationApi");
Object.defineProperty(exports, "getProviderHealth", { enumerable: true, get: function () { return communicationApi_1.getProviderHealth; } });
Object.defineProperty(exports, "listCommunicationProviders", { enumerable: true, get: function () { return communicationApi_1.listCommunicationProviders; } });
Object.defineProperty(exports, "ingestCommunicationMessage", { enumerable: true, get: function () { return communicationApi_1.ingestCommunicationMessage; } });
Object.defineProperty(exports, "sendCommunicationMessage", { enumerable: true, get: function () { return communicationApi_1.sendCommunicationMessage; } });
Object.defineProperty(exports, "syncCommunicationProvider", { enumerable: true, get: function () { return communicationApi_1.syncCommunicationProvider; } });
Object.defineProperty(exports, "listConversationThreads", { enumerable: true, get: function () { return communicationApi_1.listConversationThreads; } });
Object.defineProperty(exports, "getConversationMessages", { enumerable: true, get: function () { return communicationApi_1.getConversationMessages; } });
Object.defineProperty(exports, "markThreadRead", { enumerable: true, get: function () { return communicationApi_1.markThreadRead; } });
Object.defineProperty(exports, "archiveConversationThread", { enumerable: true, get: function () { return communicationApi_1.archiveConversationThread; } });
Object.defineProperty(exports, "analyzeConversationThread", { enumerable: true, get: function () { return communicationApi_1.analyzeConversationThread; } });
Object.defineProperty(exports, "generateConversationSummary", { enumerable: true, get: function () { return communicationApi_1.generateConversationSummary; } });
Object.defineProperty(exports, "generateAIReply", { enumerable: true, get: function () { return communicationApi_1.generateAIReply; } });
Object.defineProperty(exports, "searchCommunications", { enumerable: true, get: function () { return communicationApi_1.searchCommunications; } });
Object.defineProperty(exports, "getCommunicationStats", { enumerable: true, get: function () { return communicationApi_1.getCommunicationStats; } });
Object.defineProperty(exports, "createCommunicationTemplate", { enumerable: true, get: function () { return communicationApi_1.createCommunicationTemplate; } });
Object.defineProperty(exports, "listCommunicationTemplates", { enumerable: true, get: function () { return communicationApi_1.listCommunicationTemplates; } });
Object.defineProperty(exports, "scheduleCommunicationMessage", { enumerable: true, get: function () { return communicationApi_1.scheduleCommunicationMessage; } });
Object.defineProperty(exports, "listScheduledMessages", { enumerable: true, get: function () { return communicationApi_1.listScheduledMessages; } });
var healthApi_1 = require("./healthApi");
Object.defineProperty(exports, "getHealthProviderHealth", { enumerable: true, get: function () { return healthApi_1.getHealthProviderHealth; } });
Object.defineProperty(exports, "listHealthProviders", { enumerable: true, get: function () { return healthApi_1.listHealthProviders; } });
Object.defineProperty(exports, "createPatient", { enumerable: true, get: function () { return healthApi_1.createPatient; } });
Object.defineProperty(exports, "getPatient", { enumerable: true, get: function () { return healthApi_1.getPatient; } });
Object.defineProperty(exports, "listPatients", { enumerable: true, get: function () { return healthApi_1.listPatients; } });
Object.defineProperty(exports, "addPatientVisit", { enumerable: true, get: function () { return healthApi_1.addPatientVisit; } });
Object.defineProperty(exports, "addPatientAllergy", { enumerable: true, get: function () { return healthApi_1.addPatientAllergy; } });
Object.defineProperty(exports, "addPatientMedicalHistory", { enumerable: true, get: function () { return healthApi_1.addPatientMedicalHistory; } });
Object.defineProperty(exports, "addPatientLabResult", { enumerable: true, get: function () { return healthApi_1.addPatientLabResult; } });
Object.defineProperty(exports, "createHealthFacility", { enumerable: true, get: function () { return healthApi_1.createHealthFacility; } });
Object.defineProperty(exports, "listHealthFacilities", { enumerable: true, get: function () { return healthApi_1.listHealthFacilities; } });
Object.defineProperty(exports, "createHealthcareProvider", { enumerable: true, get: function () { return healthApi_1.createHealthcareProvider; } });
Object.defineProperty(exports, "listHealthcareProviders", { enumerable: true, get: function () { return healthApi_1.listHealthcareProviders; } });
Object.defineProperty(exports, "scheduleAppointment", { enumerable: true, get: function () { return healthApi_1.scheduleAppointment; } });
Object.defineProperty(exports, "rescheduleAppointment", { enumerable: true, get: function () { return healthApi_1.rescheduleAppointment; } });
Object.defineProperty(exports, "cancelAppointment", { enumerable: true, get: function () { return healthApi_1.cancelAppointment; } });
Object.defineProperty(exports, "completeAppointment", { enumerable: true, get: function () { return healthApi_1.completeAppointment; } });
Object.defineProperty(exports, "setAppointmentTravelTime", { enumerable: true, get: function () { return healthApi_1.setAppointmentTravelTime; } });
Object.defineProperty(exports, "listAppointments", { enumerable: true, get: function () { return healthApi_1.listAppointments; } });
Object.defineProperty(exports, "createRecurringAppointments", { enumerable: true, get: function () { return healthApi_1.createRecurringAppointments; } });
Object.defineProperty(exports, "addMedication", { enumerable: true, get: function () { return healthApi_1.addMedication; } });
Object.defineProperty(exports, "updateMedicationStatus", { enumerable: true, get: function () { return healthApi_1.updateMedicationStatus; } });
Object.defineProperty(exports, "listMedications", { enumerable: true, get: function () { return healthApi_1.listMedications; } });
Object.defineProperty(exports, "scheduleMedicationDose", { enumerable: true, get: function () { return healthApi_1.scheduleMedicationDose; } });
Object.defineProperty(exports, "recordMedicationDose", { enumerable: true, get: function () { return healthApi_1.recordMedicationDose; } });
Object.defineProperty(exports, "setMedicationRefillDate", { enumerable: true, get: function () { return healthApi_1.setMedicationRefillDate; } });
Object.defineProperty(exports, "scheduleVaccination", { enumerable: true, get: function () { return healthApi_1.scheduleVaccination; } });
Object.defineProperty(exports, "markVaccinationCompleted", { enumerable: true, get: function () { return healthApi_1.markVaccinationCompleted; } });
Object.defineProperty(exports, "listVaccinations", { enumerable: true, get: function () { return healthApi_1.listVaccinations; } });
Object.defineProperty(exports, "vaccinationDueList", { enumerable: true, get: function () { return healthApi_1.vaccinationDueList; } });
Object.defineProperty(exports, "registerDisease", { enumerable: true, get: function () { return healthApi_1.registerDisease; } });
Object.defineProperty(exports, "listDiseases", { enumerable: true, get: function () { return healthApi_1.listDiseases; } });
Object.defineProperty(exports, "registerHealthProgram", { enumerable: true, get: function () { return healthApi_1.registerHealthProgram; } });
Object.defineProperty(exports, "listHealthPrograms", { enumerable: true, get: function () { return healthApi_1.listHealthPrograms; } });
Object.defineProperty(exports, "generateDecisionSupport", { enumerable: true, get: function () { return healthApi_1.generateDecisionSupport; } });
Object.defineProperty(exports, "getHealthStats", { enumerable: true, get: function () { return healthApi_1.getHealthStats; } });
Object.defineProperty(exports, "runHealthReminderChecks", { enumerable: true, get: function () { return healthApi_1.runHealthReminderChecks; } });
Object.defineProperty(exports, "listHealthSuggestions", { enumerable: true, get: function () { return healthApi_1.listHealthSuggestions; } });
Object.defineProperty(exports, "dismissHealthSuggestion", { enumerable: true, get: function () { return healthApi_1.dismissHealthSuggestion; } });
Object.defineProperty(exports, "generateFollowUpReminder", { enumerable: true, get: function () { return healthApi_1.generateFollowUpReminder; } });
Object.defineProperty(exports, "linkMedicalReport", { enumerable: true, get: function () { return healthApi_1.linkMedicalReport; } });
var financeApi_1 = require("./financeApi");
Object.defineProperty(exports, "getFinanceProviderHealth", { enumerable: true, get: function () { return financeApi_1.getFinanceProviderHealth; } });
Object.defineProperty(exports, "listFinanceProviders", { enumerable: true, get: function () { return financeApi_1.listFinanceProviders; } });
Object.defineProperty(exports, "createBudget", { enumerable: true, get: function () { return financeApi_1.createBudget; } });
Object.defineProperty(exports, "getBudget", { enumerable: true, get: function () { return financeApi_1.getBudget; } });
Object.defineProperty(exports, "listBudgets", { enumerable: true, get: function () { return financeApi_1.listBudgets; } });
Object.defineProperty(exports, "forecastBudget", { enumerable: true, get: function () { return financeApi_1.forecastBudget; } });
Object.defineProperty(exports, "recordExpense", { enumerable: true, get: function () { return financeApi_1.recordExpense; } });
Object.defineProperty(exports, "getExpense", { enumerable: true, get: function () { return financeApi_1.getExpense; } });
Object.defineProperty(exports, "listExpenses", { enumerable: true, get: function () { return financeApi_1.listExpenses; } });
Object.defineProperty(exports, "approveExpense", { enumerable: true, get: function () { return financeApi_1.approveExpense; } });
Object.defineProperty(exports, "rejectExpense", { enumerable: true, get: function () { return financeApi_1.rejectExpense; } });
Object.defineProperty(exports, "markExpenseReimbursed", { enumerable: true, get: function () { return financeApi_1.markExpenseReimbursed; } });
Object.defineProperty(exports, "recordIncome", { enumerable: true, get: function () { return financeApi_1.recordIncome; } });
Object.defineProperty(exports, "listIncome", { enumerable: true, get: function () { return financeApi_1.listIncome; } });
Object.defineProperty(exports, "createVendor", { enumerable: true, get: function () { return financeApi_1.createVendor; } });
Object.defineProperty(exports, "listVendors", { enumerable: true, get: function () { return financeApi_1.listVendors; } });
Object.defineProperty(exports, "searchVendors", { enumerable: true, get: function () { return financeApi_1.searchVendors; } });
Object.defineProperty(exports, "evaluateVendor", { enumerable: true, get: function () { return financeApi_1.evaluateVendor; } });
Object.defineProperty(exports, "createInvoice", { enumerable: true, get: function () { return financeApi_1.createInvoice; } });
Object.defineProperty(exports, "listInvoices", { enumerable: true, get: function () { return financeApi_1.listInvoices; } });
Object.defineProperty(exports, "markInvoicePaid", { enumerable: true, get: function () { return financeApi_1.markInvoicePaid; } });
Object.defineProperty(exports, "detectOverdueInvoices", { enumerable: true, get: function () { return financeApi_1.detectOverdueInvoices; } });
Object.defineProperty(exports, "linkInvoiceDocument", { enumerable: true, get: function () { return financeApi_1.linkInvoiceDocument; } });
Object.defineProperty(exports, "recordPayment", { enumerable: true, get: function () { return financeApi_1.recordPayment; } });
Object.defineProperty(exports, "listPayments", { enumerable: true, get: function () { return financeApi_1.listPayments; } });
Object.defineProperty(exports, "createProcurementRequest", { enumerable: true, get: function () { return financeApi_1.createProcurementRequest; } });
Object.defineProperty(exports, "listProcurementRequests", { enumerable: true, get: function () { return financeApi_1.listProcurementRequests; } });
Object.defineProperty(exports, "addQuotation", { enumerable: true, get: function () { return financeApi_1.addQuotation; } });
Object.defineProperty(exports, "compareQuotations", { enumerable: true, get: function () { return financeApi_1.compareQuotations; } });
Object.defineProperty(exports, "selectVendorForRequest", { enumerable: true, get: function () { return financeApi_1.selectVendorForRequest; } });
Object.defineProperty(exports, "issuePurchaseOrder", { enumerable: true, get: function () { return financeApi_1.issuePurchaseOrder; } });
Object.defineProperty(exports, "recordGoodsReceipt", { enumerable: true, get: function () { return financeApi_1.recordGoodsReceipt; } });
Object.defineProperty(exports, "matchInvoiceToRequest", { enumerable: true, get: function () { return financeApi_1.matchInvoiceToRequest; } });
Object.defineProperty(exports, "approveProcurementRequest", { enumerable: true, get: function () { return financeApi_1.approveProcurementRequest; } });
Object.defineProperty(exports, "rejectProcurementRequest", { enumerable: true, get: function () { return financeApi_1.rejectProcurementRequest; } });
Object.defineProperty(exports, "registerAsset", { enumerable: true, get: function () { return financeApi_1.registerAsset; } });
Object.defineProperty(exports, "listAssets", { enumerable: true, get: function () { return financeApi_1.listAssets; } });
Object.defineProperty(exports, "assignAsset", { enumerable: true, get: function () { return financeApi_1.assignAsset; } });
Object.defineProperty(exports, "returnAsset", { enumerable: true, get: function () { return financeApi_1.returnAsset; } });
Object.defineProperty(exports, "scheduleAssetMaintenance", { enumerable: true, get: function () { return financeApi_1.scheduleAssetMaintenance; } });
Object.defineProperty(exports, "checkAssetMaintenanceDue", { enumerable: true, get: function () { return financeApi_1.checkAssetMaintenanceDue; } });
Object.defineProperty(exports, "disposeAsset", { enumerable: true, get: function () { return financeApi_1.disposeAsset; } });
Object.defineProperty(exports, "getFinanceStats", { enumerable: true, get: function () { return financeApi_1.getFinanceStats; } });
Object.defineProperty(exports, "getFinanceMonthlyReport", { enumerable: true, get: function () { return financeApi_1.getFinanceMonthlyReport; } });
Object.defineProperty(exports, "getFinanceYearlyReport", { enumerable: true, get: function () { return financeApi_1.getFinanceYearlyReport; } });
Object.defineProperty(exports, "runFinanceReminderChecks", { enumerable: true, get: function () { return financeApi_1.runFinanceReminderChecks; } });
Object.defineProperty(exports, "listFinanceSuggestions", { enumerable: true, get: function () { return financeApi_1.listFinanceSuggestions; } });
Object.defineProperty(exports, "dismissFinanceSuggestion", { enumerable: true, get: function () { return financeApi_1.dismissFinanceSuggestion; } });
var delegationApi_1 = require("./delegationApi");
Object.defineProperty(exports, "approveRequest", { enumerable: true, get: function () { return delegationApi_1.approveRequest; } });
Object.defineProperty(exports, "bulkApproveRequests", { enumerable: true, get: function () { return delegationApi_1.bulkApproveRequests; } });
Object.defineProperty(exports, "bulkRejectRequests", { enumerable: true, get: function () { return delegationApi_1.bulkRejectRequests; } });
Object.defineProperty(exports, "cancelRequest", { enumerable: true, get: function () { return delegationApi_1.cancelRequest; } });
Object.defineProperty(exports, "createApprovalRequest", { enumerable: true, get: function () { return delegationApi_1.createApprovalRequest; } });
Object.defineProperty(exports, "delegateRequest", { enumerable: true, get: function () { return delegationApi_1.delegateRequest; } });
Object.defineProperty(exports, "getApprovalMetrics", { enumerable: true, get: function () { return delegationApi_1.getApprovalMetrics; } });
Object.defineProperty(exports, "getApprovalPolicyBands", { enumerable: true, get: function () { return delegationApi_1.getApprovalPolicyBands; } });
Object.defineProperty(exports, "getApprovalRequest", { enumerable: true, get: function () { return delegationApi_1.getApprovalRequest; } });
Object.defineProperty(exports, "getApprovalStats", { enumerable: true, get: function () { return delegationApi_1.getApprovalStats; } });
Object.defineProperty(exports, "listApprovalHistory", { enumerable: true, get: function () { return delegationApi_1.listApprovalHistory; } });
Object.defineProperty(exports, "listApprovalRequests", { enumerable: true, get: function () { return delegationApi_1.listApprovalRequests; } });
Object.defineProperty(exports, "listApprovalTemplates", { enumerable: true, get: function () { return delegationApi_1.listApprovalTemplates; } });
Object.defineProperty(exports, "listDelegatedApprovals", { enumerable: true, get: function () { return delegationApi_1.listDelegatedApprovals; } });
Object.defineProperty(exports, "listExecutedApprovals", { enumerable: true, get: function () { return delegationApi_1.listExecutedApprovals; } });
Object.defineProperty(exports, "listExpiredApprovals", { enumerable: true, get: function () { return delegationApi_1.listExpiredApprovals; } });
Object.defineProperty(exports, "listPendingApprovals", { enumerable: true, get: function () { return delegationApi_1.listPendingApprovals; } });
Object.defineProperty(exports, "listRejectedApprovals", { enumerable: true, get: function () { return delegationApi_1.listRejectedApprovals; } });
Object.defineProperty(exports, "listUrgentApprovals", { enumerable: true, get: function () { return delegationApi_1.listUrgentApprovals; } });
Object.defineProperty(exports, "rejectRequest", { enumerable: true, get: function () { return delegationApi_1.rejectRequest; } });
Object.defineProperty(exports, "rollbackApprovalRequest", { enumerable: true, get: function () { return delegationApi_1.rollbackApprovalRequest; } });
Object.defineProperty(exports, "runApprovalScheduledChecks", { enumerable: true, get: function () { return delegationApi_1.runApprovalScheduledChecks; } });
//# sourceMappingURL=index.js.map